language: objective-c
osx_image: xcode10
dist: trusty

cache:
  directories:
  - vendor/bundle
  - Pods

addons:
  sonarcloud:
    organization: scior-github
    token:
      secure: qUWqESb69O+3YbyLeoZjNTZh9eggUjiVYm5Mn/8GPRFfm3yIe7YQzUAr3bejyd5jOiJTGFitl+iBCEhz54Cet0F6+jJGdjBR3rjbrMaMqwdpuRJkT31dQNg7zwD8DSiE8d3xhrCMNYG/aIuAU0xqAp8BQU08ONZKO6U+bEG9RFl9pF92GFkRGHXYc7T0HeW9LH2LnRzHLQb/SqBd22Z+mi1BFtwIsEZGY0tDGfJ+XFrkBTdG4SnwZlt3zZOv9DBleOiqAV4jpVQKduOZI/kJgrQdNK2etrYvAf4Q4hFe4GVfcV09j/qQUs0EW/G2EfvnCUrVXpExDPHFcfuetuH7OWuzze869W0DQ8gPI0rkXGBr1cEWAJUke129YhWyzlrmesj81HgzWUppmJ7MfN2GNRp5SgN8vsfWvDPH8WnSF+CQd/vcUUSotjebVfQLlkv5oRGXO4Wub8tRPM+UinyoV1+BADCm1Oax+YMECJRep916EuySOVg0umxBcF7bD15g4AawWZd7oxWKPZ3UjlaVwbo1IPxuVWfWrSJgbo68+90vsuMlyRMm0qtbz5pdkMwTFtCqdnRknm2Tpt4+vav4b65TB6lgwFgY9hRVbrdqmDXc6yg1YiCbNLe8zyx+tx1Z75DKxdcc+LK9Anfa8buE/bDfvqI0c9dJ/lMJjOlvWgc=

before_script:
- bundle exec danger

script: 
  - fastlane coverage
#  - find . -type d | grep -E  ".xccovarchive$" | xargs -I@ bash utils/xccov-to-sonarqube-generic.sh @ > sonarqube-generic-coverage.xml
#  - sonar-scanner -X

branches:
  only:
  - master
  - ci-test

notifications:
  slack:
    secure: LMdtNgfaKXv//cH2bRqjdz21d3vDk+ImDMeB8PskoU5eV8ThzOasnywhAwZ37MRawJLEbzvg7mT7yNg2aYKoOEB0XfVPG0T9jErleaBbOeewieJYuDu6uLT3z6PLK17CL/ocQxUMwNNTbdVzliL0NbWihonxwm2NnYs9q3YIrKv6K8zLQhf/EzVBXlBbegQCEEpqGpGEf60xY70nUmdyVnn1hYkxvF0hRZGK5ZuMGVV7jqByykSpSStndeUvT66pJHgU3gs/nKiIHrsaBgiGM8+ehEzNQSo0C9fG9BgV8SNmy3eT5Ivt42A+i8bmqe69ETgNwh3zgDDtWDD7G3yUFqXsM7cpjXdZhY8NpHBhDbf/NqTUnLlUcfOcNZARINbc5efISz0GX/AHZjZzQsd1d45knX+rtZt07Xm1KAX8Nnr6TQ19IeWNiz/xNCYhE8hB3Sre1SKU5aC9kc4HGKLkylCklg3AmmyvqqBaDtNPwFl4PDicNezOlKnC47Cntj/2tRZZOYpCY51FOwsfFQXTvtaZJLN9MzXfFx24uEobutKuwsJEn9VAetrPWTWl0LnCjw5BhAXVQ5lpN58uH5Gc31VRkLE+chzAzSMDvSOjmvylBwMhZt7V4Uw4ndXuxEYHFfMyiznd9iX4xx+s8QsQoQ7Qubm1819rZJRQJR0IO0Y=

