language: objective-c
osx_image: xcode10
dist: trusty

cache:
  directories:
  - vendor/bundle
  - Pods

addons:
  sonarcloud:
    organization: scior-github
    token:
      secure: qUWqESb69O+3YbyLeoZjNTZh9eggUjiVYm5Mn/8GPRFfm3yIe7YQzUAr3bejyd5jOiJTGFitl+iBCEhz54Cet0F6+jJGdjBR3rjbrMaMqwdpuRJkT31dQNg7zwD8DSiE8d3xhrCMNYG/aIuAU0xqAp8BQU08ONZKO6U+bEG9RFl9pF92GFkRGHXYc7T0HeW9LH2LnRzHLQb/SqBd22Z+mi1BFtwIsEZGY0tDGfJ+XFrkBTdG4SnwZlt3zZOv9DBleOiqAV4jpVQKduOZI/kJgrQdNK2etrYvAf4Q4hFe4GVfcV09j/qQUs0EW/G2EfvnCUrVXpExDPHFcfuetuH7OWuzze869W0DQ8gPI0rkXGBr1cEWAJUke129YhWyzlrmesj81HgzWUppmJ7MfN2GNRp5SgN8vsfWvDPH8WnSF+CQd/vcUUSotjebVfQLlkv5oRGXO4Wub8tRPM+UinyoV1+BADCm1Oax+YMECJRep916EuySOVg0umxBcF7bD15g4AawWZd7oxWKPZ3UjlaVwbo1IPxuVWfWrSJgbo68+90vsuMlyRMm0qtbz5pdkMwTFtCqdnRknm2Tpt4+vav4b65TB6lgwFgY9hRVbrdqmDXc6yg1YiCbNLe8zyx+tx1Z75DKxdcc+LK9Anfa8buE/bDfvqI0c9dJ/lMJjOlvWgc=

before_script:
  - bundle exec danger

script:
  - fastlane coverage

branches:
  only:
  - master
  - ci-test

notifications:
  slack:
    secure: aqH//ZmcwhTV5nIgeLhcSXIsMNbNRP6KizujmZiiFSgFh9lfgsvq79g1UvWDDmWydH5mru2trph3q1sYg866afPK7jxWNXkz4eA9RroWY3JROC4WTNnvVXCSpMBpm+bKIYoeKtDjSiE+6FnawpnXzRuqYdHDX3I2zYr0LMkduhBQBeQmw76UVTAgDZUREebX5aIWfjQFyd4Moh06lHQra3Ikyoan0j3xJmVH8LbaGSIBMUN9CMtWp1IueQ0yevHOpSIB+WZ+YONpT9LhOwyLpuyG22THalMRcv+BVnt53AS5bJpr6B89ejZl3JtpFEet2OSWS6pjoUNhnqo8mkavinyZ3waRSKbrx4B70s587sxf5FhCVBh2zVDj315EyydSPfhqLhg3Uo1Ck0KT4m241GAhmGJuU4oaqXZXjKViEXbyiPI8qoBc5bnfUg3vE1ZgbN2c+cS//n84SIo86feDKeBDbdSCZybjUsKOBwY54XohR6iEdeczBoRQV6gl6LQxrM/VH+me8DeI9ZfOPgE73iIotiEPIqHdfvE9J8APEneHdLjqSVfiN2OiMQk4E0n2x8jBQDqx4hZZivJBRGHzGXb70ewdRRDl2EPofMf5By2j4blgvOKWXc2yZr5EFUllFVzO0hwVhQvNXVYPErr1Rk1ic1TwpgC5cA4Ljtwadyw=
