language: objective-c
osx_image: xcode10
dist: trusty

cache:
  directories:
  - vendor/bundle
  - Pods
  - Carthage

addons:
  sonarcloud:
    organization: scior-github
    token:
      secure: "QEtUVTnAX4RlaNHV5Jpc0cIwQB2X4InKUc4vZu3C7Cluz82M11IiQ7kDxk/h4H5HfoNTxq8C7U7RKZYn2OEXVnzO0aNcp2bPiOliTCo0tOgCrPnlj/LXrPP0xN8lkE0AJlebZtwOExw5xuwVkfhjDxsHw9Xk+7gIK9V8N+7ZxpgAJp/mzV5q/92QcJlvq3VK7zfKjyqP4Xyf3hkyH0j0Z/Xg8f8w/7NUB14x6VIYjZaiTFSLlB3CVtsVHQil0QWdJdveytMQnxXT9GD1jEucNUScTjQqmAgqAS0aD0wM3aB7kyRPtsMX3Rv5ZOWN1LgC38Jvn9uNksrAc34GR3yuFuDFdH1ejpwJRaeGZNvSMjAuAzX7GrMH1+f8bq0paHEW4QAuYOrlTbC5d8D4gEFKM27yRzM2508aWXo9euW3ZwTi3QNN7T5bkg4SM2hdBkvRxTS5C/5FzaWz+urzrUgA0X8AYH84bXmR3EpklAG71cP5QCrNR7IWciMThqBXTfNV7D3ynMlw/uvLF7C6L1vYSgQcgp21KAYuNNU1Vu1tiBGazODOWkwaOYKhoKdeumUjhSmgqE55tP98hN9joDowubi6CQk0TLZnPDbvZI47Mt4q7QmR9/zMwKB9w/Qp6RzueJ+83xEEdixgkbDN7AyeO0w3Z+wVdL//pE1bCYuZ66U="

before_script:
  - bundle exec danger

script:
  - fastlane coverage
  - find . -type d | grep -E  ".xccovarchive$" | xargs -I@ bash utils/xccov-to-sonarqube-generic.sh @ > sonarqube-generic-coverage.xml
  - sonar-scanner -X

branches:
  only:
  - master
  - ci-test

notifications:
  slack:
    secure: aqH//ZmcwhTV5nIgeLhcSXIsMNbNRP6KizujmZiiFSgFh9lfgsvq79g1UvWDDmWydH5mru2trph3q1sYg866afPK7jxWNXkz4eA9RroWY3JROC4WTNnvVXCSpMBpm+bKIYoeKtDjSiE+6FnawpnXzRuqYdHDX3I2zYr0LMkduhBQBeQmw76UVTAgDZUREebX5aIWfjQFyd4Moh06lHQra3Ikyoan0j3xJmVH8LbaGSIBMUN9CMtWp1IueQ0yevHOpSIB+WZ+YONpT9LhOwyLpuyG22THalMRcv+BVnt53AS5bJpr6B89ejZl3JtpFEet2OSWS6pjoUNhnqo8mkavinyZ3waRSKbrx4B70s587sxf5FhCVBh2zVDj315EyydSPfhqLhg3Uo1Ck0KT4m241GAhmGJuU4oaqXZXjKViEXbyiPI8qoBc5bnfUg3vE1ZgbN2c+cS//n84SIo86feDKeBDbdSCZybjUsKOBwY54XohR6iEdeczBoRQV6gl6LQxrM/VH+me8DeI9ZfOPgE73iIotiEPIqHdfvE9J8APEneHdLjqSVfiN2OiMQk4E0n2x8jBQDqx4hZZivJBRGHzGXb70ewdRRDl2EPofMf5By2j4blgvOKWXc2yZr5EFUllFVzO0hwVhQvNXVYPErr1Rk1ic1TwpgC5cA4Ljtwadyw=
